sudo: required
dist: trusty

services:
  - docker

language: cpp

env:
  matrix:
    - COMPILER=gcc
    - COMPILER=llvm

# command to install dependencies
install:
  - shopt -s extglob dotglob
  - mkdir Package
  - mv !(Package) Package
  - shopt -u dotglob
  - export PKGDIR=${PWD}/Package
  - curl -O https://lcd-data.web.cern.ch/lcd-data/CernVM/cernvm3-docker-latest.tar
  - cat cernvm3-docker-latest.tar | docker import - cernvm
  - export description=`date`
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${COMPILER}" == "gcc"  ]];
    then wget https://scan.coverity.com/download/linux64 --post-data "token=${COVERITY_SCAN_TOKEN}&project=iLCSoft%2FOverlay" -O Package/coverity_tool.tgz; cd Package; mkdir cov-analysis-linux64; tar -xf coverity_tool.tgz -C cov-analysis-linux64 --strip-components=2;
    fi

# command to run tests
script:
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${COMPILER}" == "gcc"  ]];
    then docker run -t  -v $PKGDIR:/Package cernvm /init /Package/.travis-ci.d/coverity_scan.sh;
    elif [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${COMPILER}" == "llvm"  ]];
    then echo "Running the weekly Coverity Scan, no LLVM/Clang build this time";
    else docker run -t -v $PKGDIR:/Package -e COMPILER=${COMPILER} cernvm /init /Package/.travis-ci.d/compile_and_test.sh;
    fi
  - if [[ "${TRAVIS_EVENT_TYPE}" == "cron" && "${COMPILER}" == "gcc"  ]];
    then curl --form token=${COVERITY_SCAN_TOKEN} --form email=marko.petric@cern.ch --form file=@Package/build/myproject.tgz --form version="master" --form description="${description}" https://scan.coverity.com/builds?project=iLCSoft%2FOverlay ;
    fi

# Don't send e-mail notifications
notifications:
  email: false
